config/routes.rb
Rails.application.routes.draw do


  resources :memos
  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }
  root 'timeline#index'

  # ## タイムライン
  get 'timeline/index'

  # ## ユーザー一覧、詳細
  get 'user/index'
  match 'user/:user_id', :controller => :user, :action => :show, :via => :get

  # ## ツイート投稿, 詳細
  get 'tweet/new'
  match 'tweet/new', :controller => :tweet, :action => :create, :via => :post
  match 'tweet/:tweet_id', :controller => :tweet, :action => :show, :via => :get
  match 'tweet/delete/:tweet_id', :controller => :tweet, :action => :destroy, :via => :delete

  # ## フォロー処理
  get 'follow/index'
  match 'follow', :controller => :follow, :action => :create, :via => :post
  match 'follow', :controller => :follow, :action => :redirect, :via => :get
  match 'follow', :controller => :follow, :action => :destroy, :via => :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :follow_user, foreign_key: 'follow_user_id', class_name: 'User'

  class << self
    def find_relation(from_id, to_id)
      follow = Follow.find_by(user_id: from_id, follow_user_id: to_id)
      return follow.present?
    end

    def user_ids
      all.map{|follow| follow[:user_id]}
    end

    def follow_ids
      all.map{|follow| follow[:follow_user_id]}
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets

  has_many :follows
  has_many :user, through: :follows


  validates :user_name, presence: true

  def name
    user_name.empty? ? '<empty>' : user_name
  end

end

app/controllers/follow_controller.rb
class FollowController < ApplicationController

  before_filter :authenticate_user!

  # ## フォロー一覧
  def index
    @follows = current_user.follows
    @follow_ids = @follows.follow_ids
    @followers = Follow.where(follow_user_id: current_user.id)
  end

  # ## フォロー処理
  def create
    @follow_user = User.find_by(id: params[:follow_user_id])
    if @follow_user.blank?
      redirect_to root_path, :alert => '無効なユーザーです'
      return
    end
    if Follow.find_relation(current_user.id, params[:follow_user_id])
      redirect_to root_path, :alert => 'フォロー済みです'
      return
    end

    follow = Follow.create(user_id: current_user.id, follow_user_id: params[:follow_user_id])
    if follow.save!
      @message = "#{@follow_user.name}をフォローしました"
    else
      @message = 'フォローに失敗しました'
    end
  end

  # ## アンフォロー処理
  def destroy
    @follow_user = User.find_by(id: params[:follow_user_id])
    if @follow_user.blank?
      redirect_to root_path, :alert => '無効なユーザーです'
      return
    end
    unless Follow.find_relation(current_user.id, params[:follow_user_id])
      redirect_to root_path, :alert => 'フォローしていません'
      return
    end

    follow = Follow.find_by(user_id: current_user.id, follow_user_id: params[:follow_user_id])
    if follow.destroy!
      @message = "#{@follow_user.name}をアンフォローしました"
    else
      @message = 'アンフォローに失敗しました'
    end
  end

  def redirect
    redirect_to root_path
  end
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/views/follow/create.html.erb
<h1>フォロー</h1>
<p><%= @message %></p>

<%= link_to '戻る', :back %>

app/views/follow/delete.html.erb
<h1>アンフォロー</h1>
<p><%= @message %></p>

<%= link_to '戻る', :back %>

app/views/follow/index.html.erb
<h1>フォロー</h1>

<table border="1">
  <tr>
    <th>ユーザー名</th>
    <th>フォロー日時</th>
    <th>フォローボタン</th>
  </tr>
  <% for follow in @follows %>
    <tr>
      <td>
        <%= follow.follow_user.name %>
      </td>
      <td>
        <%= follow.created_at %>
      </td>
      <td>
        <%= link_to 'アンフォロー', follow_path(follow_user_id: follow.follow_user.id), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

<h1>フォロワー</h1>

<table border="1">
  <tr>
    <th>ユーザー名</th>
    <th>フォロー日時</th>
    <th>フォローボタン</th>
  </tr>
  <% for follow in @followers %>
      <tr>
        <td>
          <%= follow.user.name %>
        </td>
        <td>
          <%= follow.created_at %>
        </td>
        <td>
          <% if current_user.present? %>
              <% if @follow_ids.include? follow.user.id %>
                  <%= link_to 'アンフォロー', follow_path(follow_user_id: follow.user.id), method: :delete %>
              <% else %>
                  <%= link_to 'フォロー', follow_path(follow_user_id: follow.user.id), method: :post %>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>