config/routes.rb
Rails.application.routes.draw do


  resources :memos
  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }
  root 'timeline#index'

  # ## タイムライン
  get 'timeline/index'

  # ## ユーザー一覧、詳細
  get 'user/index'
  match 'user/:user_id', :controller => :user, :action => :show, :via => :get

  # ## ツイート投稿, 詳細
  get 'tweet/new'
  match 'tweet/new', :controller => :tweet, :action => :create, :via => :post
  match 'tweet/:tweet_id', :controller => :tweet, :action => :show, :via => :get
  match 'tweet/delete/:tweet_id', :controller => :tweet, :action => :destroy, :via => :delete

  # ## フォロー処理
  get 'follow/index'
  match 'follow', :controller => :follow, :action => :create, :via => :post
  match 'follow', :controller => :follow, :action => :redirect, :via => :get
  match 'follow', :controller => :follow, :action => :destroy, :via => :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:user_id, :header, :body)
    end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<%= form_for(memo) do |f| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :header %>
    <%= f.text_field :header %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Header</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.user_id %></td>
        <td><%= memo.header %></td>
        <td><%= memo.body %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @memo.user_id %>
</p>

<p>
  <strong>Header:</strong>
  <%= @memo.header %>
</p>

<p>
  <strong>Body:</strong>
  <%= @memo.body %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>