config/routes.rb
Rails.application.routes.draw do


  resources :memos
  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }
  root 'timeline#index'

  # ## タイムライン
  get 'timeline/index'

  # ## ユーザー一覧、詳細
  get 'user/index'
  match 'user/:user_id', :controller => :user, :action => :show, :via => :get

  # ## ツイート投稿, 詳細
  get 'tweet/new'
  match 'tweet/new', :controller => :tweet, :action => :create, :via => :post
  match 'tweet/:tweet_id', :controller => :tweet, :action => :show, :via => :get
  match 'tweet/delete/:tweet_id', :controller => :tweet, :action => :destroy, :via => :delete

  # ## フォロー処理
  get 'follow/index'
  match 'follow', :controller => :follow, :action => :create, :via => :post
  match 'follow', :controller => :follow, :action => :redirect, :via => :get
  match 'follow', :controller => :follow, :action => :destroy, :via => :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterModoki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="background: #eee">
        <nav>
          <%= link_to "ホーム", root_path %>
          <%= link_to "ユーザー一覧", user_index_path %>
          <% if user_signed_in? %>
              <p>ろぐいん: <%= current_user.name %> さんこんにちは</p>
              <%= link_to "新規ツイート", tweet_new_path %>
              <%= link_to "フォロー/フォロワー", follow_index_path %>
              <%= link_to "設定", {:controller => "users/registrations", :action => "edit"} %>
              <%= link_to "ログアウト", {:controller => "users/sessions", :action => "destroy"}, :method => :delete%>
          <% else %>
              <p>非ろぐいん: ログインしましょう</p>
              <%= link_to "ログイン", {:controller => "users/sessions", :action => "create"} %>
              <%= link_to "新規登録", {:controller => "users/registrations", :action => "new"} %>
          <% end %>
        </nav>
    </header>
    <p class="notice" style="background: #00aa00"><%= notice %></p>
    <p class="alert" style="background: #aa5555"><%= alert %></p>

    <%= yield %>
  </body>
</html>